# To learn more about Dependabot configuration at Chime, visit: http://go/dependabot-configuration
name: "Dependabot Automerge"

on: pull_request_target

jobs:
  auto-merge:
    if: startsWith(github.head_ref, 'dependabot')
    runs-on: ubuntu-24.04
    steps:
      # Check if auto merges/deploys are allowed
      - name: Auto Merges/deploys allowed?
        uses: 1debit/pr-auto-merge-action@v1
      # Check if PR can be auto-approved
      - uses: actions/checkout@v4
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: "${{ secrets.DEPENDABOT_AUTO_MERGE_GITHUB_TOKEN }}" # chime-dependency-bot user token
          config: .github/dependabot-auto-merge.config.yml
          command: "squash and merge"
